### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by deployable** [blackwinter/ruby-filemagic#10]
Compiling ruby-filemagic on Windows caused me some problems due to the dependencies. Ended up requiring the following:

Download file-5.21.tar.gz from ftp://ftp.astron.com/pub/file/ and extract somewhere. 

Download libgnurx 2.5.1 [bin](http://sourceforge.net/projects/mingw/files/Other/UserContributed/regex/mingw-regex-2.5.1/mingw-libgnurx-2.5.1-bin.tar.gz/download) + [dev](http://sourceforge.net/projects/mingw/files/Other/UserContributed/regex/mingw-regex-2.5.1/mingw-libgnurx-2.5.1-dev.tar.gz/download) from [sourceforge](http://sourceforge.net/projects/mingw/files/Other/UserContributed/regex/mingw-regex-2.5.1/) and extract somewhere

Build `file`

     LDFLAGS=-L/a/path/to/libgnurx-2.5.1/lib
     CFLAGS=-I/a/path/to/libgnurx-2.5.1/include
     ./configure --prefix=/a/path/to/file-2.21
     make install

From inside the DevKit msys shell

    gem install ruby-filemagic -- --with-magic-dir=/a/path/to/file-2.21

It would be nice if there were precompiled libraries including the Magic for Windows platforms.

**Comment by mscharley** [comment]
Any chance of a x64 release of this? Or any way to help?

**Comment by blackwinter** [comment]
@mscharley Could you please open a new issue for this? I think Windows x64 support is a different matter and deserves a discussion of its own.

**Comment by blackwinter** [comment]
@deployable I've pushed another prerelease with only minor modifications. It would be great if you could give it a final check. I'm ignoring the test failure for "pyfile-compressed" for now since I don't know whether it's caused by Windows or by newer libmagic. I'm skipping `test_check` on Windows since I don't know why this one fails either; but I have added `test_check_compiled` which does work on Windows.

Regarding x64 support, please see my previous comment.

**Comment by deployable** [comment]
All good, just the 1 test failure for `"pyfile-compressed"` as you mentioned in 1.9.3 and 2.1.5.

I'd guess pyfile-compressed is the lack of `zlib.h` as you define the `FileMagic::MAGIC_COMPRESS` flag. It appears libmagic has some [fallback support to exec compression programs](https://github.com/file/file/blob/master/src/compress.c#L68-L85) for systems with `fork`, which seems a bit horrible. 

You could enforce the zlib requirement in [extconf.rb](https://github.com/blackwinter/ruby-filemagic/blob/2bd39ffa9ecd15a6f9b7dbe9a1b0981f24d7196a/ext/filemagic/extconf.rb).  Then any chance of the exec stuff goes away but you might have to add zlib to your windows build?

**Comment by blackwinter** [comment]
Thanks for testing and also for investigating the failing test case. Unfortunately, zlib is not the issue here since Windows does not support `fork`. I'll just account for the fact that `file` won't look inside compressed files on Windows (3a89045). So unless you have any objections, I'll probably release the new version later this week.

**Comment by blackwinter** [comment]
Yes, that's what I thought too. But [as you can see](/file/file/blob/master/src/compress.c#L305-L531), all the (relevant) uses of `BUILTIN_DECOMPRESS` are wrapped by `#if HAVE_FORK` ;)

**Comment by deployable** [comment]
Ah I see!

**Comment by blackwinter** [comment]
I have released version [0.6.2](https://rubygems.org/gems/ruby-filemagic/versions/0.6.2) with precompiled extensions for Ruby 1.9, 2.0, 2.1 and 2.2 on [x86-mingw32](https://rubygems.org/gems/ruby-filemagic/versions/0.6.2-x86-mingw32) and [x86-mswin32-60](https://rubygems.org/gems/ruby-filemagic/versions/0.6.2-x86-mswin32-60). Thank you for your contribution.
